version: "3"
services: 
  app: 
    build: 
      context: .
      network: host
    container_name: flaskflutter
    restart: unless-stopped
    image: flaskflutter
    ports: 
      - '5000:5000'
      - '8080:8080'
    links:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports: 
      - '27017:27017'  
        